### ISSUE TITLE
test number must less than total number

### ISSUE THREAD

**Issue by gluttony-10** [hscspring/hcgf#10]
![QQ截图20230403182923](https://user-images.githubusercontent.com/52977964/229484683-cb6e28da-c6fa-4528-ad69-dd51dd3c633e.png)
请问遇到这种情况怎么办。我稍微修改了一下代码，发现这两个值都是0。

**Comment by hscspring** [comment]
数据集没加载进去吧。可以先按README跑通。

**Comment by gluttony-10** [comment]
![QQ截图20230404122455](https://user-images.githubusercontent.com/52977964/229686746-3905a9b3-c3e8-4516-b6d8-f8e0ac17fa95.png)
![QQ截图20230404120548](https://user-images.githubusercontent.com/52977964/229686819-55c977c1-44be-4b4c-9c4e-e78c2b0f23ee.png)
我刚更新了库，用最简单的参数，加载test下的数据集。请问可能是哪里有问题？

**Comment by hscspring** [comment]
看起来好像是数据都没读进去。。。
Linux和Mac都做了测试，Windows没测过，你可以先跑一下单元测试看看。

```bash
python -m pytest 
```
