### ISSUE TITLE
如设置微调模型保存步数？

### ISSUE THREAD

**Issue by qianglegend** [hscspring/hcgf#13]
新手求教，如何设置训练停止步数和保存微调模型？

**Comment by hscspring** [comment]
可以设置Epoch，README有tune方法的参数。Epoch会更加直观一些（就是你所有数据跑几轮）。

训练时会每隔一段时间(1/3Epoch）验证一次，有效果提升（用验证集的loss判断）就自动保存。再就是训练完保存。

你可以直接设置Epoch就行，要停的时候直接退出进程就好了。这些参数本来可以放出来的，但是感觉没必要，还会对不熟悉AI领域的人造成困惑。
项目设计的目的就是尽量简单、减少参数，不太改动参数。
