### ISSUE TITLE
RuntimeError: Internal: [MASK] is already defined.

### ISSUE THREAD

**Issue by zhuweida222** [hscspring/hcgf#14]
微调过一次后再读取模型出现这个报错，帮忙看一下，谢谢

**Comment by zhuweida222** [comment]
![image](https://user-images.githubusercontent.com/53260235/230541252-f459954b-0294-49d6-862d-bcc1826ba460.png)

**Comment by JulyFinal** [comment]
我也是，最新的不行，用上一个版本的chatglm-6b 可以
```
gl = hcgf.GlmLora("THUDM/chatglm-6b", device="cuda:0")
```
中的` THUDM/chatglm-6b `改为
```
~/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/551a50efec3acc5a9b94de8ec46d33d0f81919f7
```

**Comment by zhuweida222** [comment]
多谢，我现在没有上一个版本的了怎么办呀，哪里可以下载嘛

**Comment by JulyFinal** [comment]
你先把这个项目`https://huggingface.co/THUDM/chatglm-6b`用git拉下来，然后check到55那次就可以了

`git reset --hard 551a50efec3acc5a9b94de8ec46d33d0f81919f7`

**Comment by hscspring** [comment]
@zhuweida222 看了一下，昨天更新了支持slim版本。连模型文件都更新了。@JulyFinal 正解。

**Comment by panpan73** [comment]
> 

请问切换完要怎么在代码hcgf.GlmLora("xxx", device="cuda:0")中生效呢

**Comment by hscspring** [comment]
这个是自动的。Transformer会自动找到这个位置。默认用的是Transformer的cache。

**Comment by panpan73** [comment]
> 

@hscspring 那我是要把chatglm-6b的commit_id 为 55 的模型拷贝到~/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/这个目录下吗

**Comment by hscspring** [comment]
不是，它是个git，你看 @JulyFinal 发的那个：

git reset --hard 551a50efec3acc5a9b94de8ec46d33d0f81919f7

就是切换一下

**Comment by JulyFinal** [comment]
> > 
> 
> @JulyFinal 请问切换完要怎么在代码hcgf.GlmLora("xxx", device="cuda:0")中生效呢

你只需要把这个xxx换成你clone下来的地址就行

**Comment by hscspring** [comment]
已经修复了，支持到最新版的ChatGLM了。

**Comment by OneStepAndTwoSteps** [comment]
已经修复了吗，我运行的时候还是出现了这样的问题 Q Q

**Comment by hscspring** [comment]
@OneStepAndTwoSteps @panpan73 

之前还有点小地方没有确认和测试。所以只是提交了代码，没有发版本。现在已经发了新版，可正常使用。

如果要使用历史版本，可以阅读README。
