### ISSUE TITLE
换成大的数据集之后显存不够

### ISSUE THREAD

**Issue by puppet101** [hscspring/hcgf#18]
如题，开始用800条数据训练，显存只有10几个g，换成5万条数据之后，现在32g显存直接溢出了，这个是什么原因呢

**Comment by hscspring** [comment]
其它参数呢？

**Comment by puppet101** [comment]
其他参数没变，但是我新的数据集文本长度增加了，会不会导致显存会随着最大文本长度而增长？ 我重新把max_seq_length改成256（之前是2048，原始的800条数据也能跑），现在显存不会溢出了
