### ISSUE TITLE
示例中chatgpt_finetune_faq.json找不到

### ISSUE THREAD

**Issue by wjjc1017** [hscspring/hcgf#3]
示例中chatgpt_finetune_faq.json找不到，请问这个文件从哪里可以下载，我想了解格式，自己微调一下。谢谢

**Comment by hscspring** [comment]
嗯，自己写一下就行，也可以不要「问题：」，prompt+completion就可以了。
这个「问题」是ChatGLM暴露出来的，可能是它输入的语料格式。
