### ISSUE TITLE
ModuleNotFoundError: No module named 'hcgf'

### ISSUE THREAD

**Issue by jlliushi** [hscspring/hcgf#6]
import hcgf
gl = hcgf.GlmLora("model", load_in_8bit=True, lora_r=32)
-----------------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15056\644290863.py in <module>
----> 1 import hcgf
      2 gl = hcgf.GlmLora("model", load_in_8bit=True, lora_r=32)

ModuleNotFoundError: No module named 'hcgf'
===================================================================================
gl.load_data("./tests/test_data.json").tune()
-----------------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15056\3044540026.py in <module>
----> 1 gl.load_data("./tests/test_data.json").tune()

NameError: name 'gl' is not defined

**Comment by hscspring** [comment]
先按README安装一下

**Comment by jlliushi** [comment]
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

**Comment by jlliushi** [comment]
我的py310环境运行ChatGLM-6B正常，运行 import hcgf 时出现以上错误信息

**Comment by jlliushi** [comment]
原来的pytorch版本时11.7，重新安装了11.8的，错误信息消除了

**Comment by jlliushi** [comment]
Loading tokenizer and model of model
Traceback (most recent call last):
  File "D:\hcgf\8bitwt.py", line 2, in <module>
    gl = hcgf.GlmLora("model", load_in_8bit=True)
  File "D:\hcgf\hcgf\sft\lora_ft.py", line 39, in __init__
    import bitsandbytes as bnb
ModuleNotFoundError: No module named 'bitsandbytes'

**Comment by jlliushi** [comment]
装上 bitsandbytes 模块后错误依然如故

CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:

**Comment by hscspring** [comment]
如果内存足够的话可以不用8bit版本。这个包是8bit版本要安装的。

**Comment by jlliushi** [comment]
我的显卡是4070Ti，12G的，应该用这个吧。ChatGlM-6B本地部署都好使了，还有Stable_Diffusion、codeFormer等AI程序都能运行，为什么本程序提示CUDA Setup failed呢？

**Comment by hscspring** [comment]
把执行过程和错误都发一下看看。这个应该是你的环境哪里没弄好。

**Comment by jlliushi** [comment]
![cw](https://user-images.githubusercontent.com/128881896/229702683-53587dbb-20d3-4f17-a54b-930f421ea88a.png)

**Comment by zhaodice** [comment]
建议conda隔离环境，一个环境一个项目，虽然浪费一点磁盘空间但是值得。
项目太多了，难免会A项目要2版本，B项目要3版本，又不能兼得。

**Comment by jlliushi** [comment]
终于鼓捣好使了：Windows10系统安装 bitsandbytes 时，需要这样
pip install bitsandbytes-windows

**Comment by hscspring** [comment]
ok，Windows开发真要命。。。

**Comment by zhaodice** [comment]
linux和windows各有各的好处吧，但我都想用，我就主系统装了Proxmox VE，然后开windows虚拟机、linux虚拟机、容器什么的，想用随时切，游戏训练两不误，想组装学习机可以参考一下～

**Comment by jlliushi** [comment]
微调后对本领域问题回答完全胡说八道！在已有本领域问答对文本的情况下，如何才能令其精准回答本领域的问题呢？还有什么好办法吗？

**Comment by hscspring** [comment]
这里有两个问题：
1. 一些简单问题微调后是能生效的，2-3轮就可以了。数据可以一定重复。不过感觉任务不能太复杂，主要是这个模型本身太小了。
2. 要想精准有点困难，毕竟是生成式模型。有两种思路可以稍微缓解这个不确定生成的问题：第一种，先做文档召回，然后召回结果作为上下文，强制模型根据上下文回答；第二种，调整参数，调用`stream_chat`方法，设置tempreture和top_p，两个不要同时用。越大越随机。
